name: needy_new
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.13.5
  syncfusion_flutter_charts: ^1.0.0-beta.4
  intl: ^0.16.1
  cupertino_icons: ^0.1.2
  firebase_messaging: ^6.0.13
  carousel_slider: ^2.0.0
  background_fetch: ^0.5.1
  spritewidget: ^0.9.24
  path_provider: ^1.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  firebase_auth: ^0.16.0 # new
  firebase_database: ^3.1.5 # new

flutter:
  uses-material-design: true

  fonts:
    - family: PressStart2P
      fonts:
        - asset: fonts/PressStart2P-Regular.ttf
    - family: Pixelar
      fonts:
        - asset: fonts/PixelarRegularW01Regular.ttf
  assets:
    - images/pixil-cat.png
    - images/pixil-bat.png
    - images/pixil-hamster.png
    - images/pixil-axolotl.png
    - images/pixil-sloth.png
    - images/catgif.gif
    - images/grass.png
    - lib/game/assets/grass.png
    - lib/game/assets/sprites.json
    - lib/game/assets/sprites.png
    - lib/game/assets/game_ui.png
    - lib/game/assets/game_ui.json
